### ISSUE TITLE
Error Too many open files

### ISSUE THREAD

**Issue by hideme4u** [saracen/walker#7]
When using for walking 500 depth nested directories {1/2/3/4 ...500} program stops with error in opening saying "Too many open files"
As walker is using go routines to walk through using readdir which at some point goes into issue of Too many open files.

@saracen  Can we expect some criteria here for how much is supported  that would help ?

**Comment by saracen** [comment]
Hey @hideme4u

Sorry for the really late reply. This library limits the amount of go rountines, currently capping it to the whatever is reported from `runtime.NumCPU()`. Was this trouble on a server with many CPUs?

Another way of hitting this problem is if your callback function is opening the files returned and not closing them.

**Comment by saracen** [comment]
I'm going to assume the problem was the callback function not closing files.

We can reopen if not the case.
